#!/bin/sh

item=$(xclip -o -selection primary)
directory=$(xprop -id $(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2) _NET_WM_NAME | cut -d '=' -f 2 | cut -b 1-2 --complement | rev | cut -c 2- | rev | sed -nr 's/(.*:)(.*)/\2/p')
directory=$(echo $directory | sed -nr 's/(~)(.*)/\/home\/ken_nc\2/p')

case $item in
    *\.jpg | *\.png)
        sel=$(printf "sxiv\npage\nfeh" | 91menu)
        [ "$sel" = "sxiv" ] && $(sxiv "$directory/$item") 2> /dev/null
        [ "$sel" = "page" ] && $(page "$directory/$item") 2> /dev/null
        [ "$sel" = "feh" ] && $(feh "$directory/$item") 2> /dev/null
        ;;
    *\.mp4 | *\.webm | *\.mov | *\.mkv)
        sel=$(printf "mpv\n" | 91menu)
        [ "$sel" = "mpv" ] && $(mpv "$directory/$item") 2> /dev/null
        ;;
    *\.pdf)
        sel=$(printf "zathura\n" | 91menu)
        [ "$sel" = "zathura" ] && $(zathura "$directory/$item") 2> /dev/null
        ;;
    *)
        sel=$(printf "cd\nedit\nexit\n" | 91menu)
        if [ "$sel" = "cd" ]; then
            termite --directory="$directory/$item"
        fi
        [ "$sel" = "acme" ] && edwood "$directory/$item"
        [ "$sel" = "exit" ] && exit 0
esac
